// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Enums.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Schema.Protobuf.Enums {

  /// <summary>Holder for reflection information generated from Enums.proto</summary>
  public static partial class EnumsReflection {

    #region Descriptor
    /// <summary>File descriptor for Enums.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgtFbnVtcy5wcm90bxIVU2NoZW1hLlByb3RvYnVmLkVudW1zKjQKCUVycm9y",
            "Q29kZRIRCg1FcnJvckNvZGVGYWlsEAASFAoQRXJyb3JDb2RlU3VjY2VzcxAB",
            "Ko4BCgxQbGF0Zm9ybVR5cGUSFwoTUGxhdGZvcm1UeXBlV2luZG93cxAAEhoK",
            "FlBsYXRmb3JtVHlwZUdvb2dsZVBsYXkQARIaChZQbGF0Zm9ybVR5cGVHYW1l",
            "Q2VudGVyEAISFQoRUGxhdGZvcm1UeXBlU3RlYW0QAxIWChJQbGF0Zm9ybVR5",
            "cGVEZXZpY2UQBCoxCgpCYXR0bGVUeXBlEhEKDUJhdHRsZVR5cGVGRkEQABIQ",
            "CgxCYXR0bGVUeXBlVEYQASovCglDbGFzc1R5cGUSEAoMQ2xhc3NUeXBlSnVu",
            "EAASEAoMQ2xhc3NUeXBlQXJhEAEqnAEKCENoYXRUeXBlEhIKDkNoYXRUeXBl",
            "Tm9ybWFsEAASEwoPQ2hhdFR5cGVXaGlzcGVyEAESEQoNQ2hhdFR5cGVQYXJ0",
            "eRACEhAKDENoYXRUeXBlQ2xhbhADEhgKFENoYXRUeXBlR2FtZUV2ZXJ5b25l",
            "EAQSFAoQQ2hhdFR5cGVHYW1lVGVhbRAFEhIKDkNoYXRUeXBlU3lzdGVtEAYq",
            "8gEKCEl0ZW1UeXBlEg8KC0l0ZW1UeXBlTm9uEAASEAoMSXRlbVR5cGVDYXNo",
            "EAESEAoMSXRlbVR5cGVHb2xkEAISFgoSSXRlbVR5cGVFeHBlcmllbmNlEAMS",
            "FQoRSXRlbVR5cGVDaGFyYWN0ZXIQBBIQCgxJdGVtVHlwZVNraW4QBRISCg5J",
            "dGVtVHlwZUhlbG1ldBAGEhEKDUl0ZW1UeXBlQXJtb3IQBxISCg5JdGVtVHlw",
            "ZVBvdGlvbhAIEhAKDEl0ZW1UeXBlQnVmZhAJEhIKDkl0ZW1UeXBlQnVuZGxl",
            "EAoSDwoLSXRlbVR5cGVCb3gQCyqCAQoQQWNoaWV2ZW1lbnRHcmFkZRIaChZB",
            "Y2hpZXZlbWVudEdyYWRlQnJvbnplEAASGgoWQWNoaWV2ZW1lbnRHcmFkZVNp",
            "bHZlchABEhgKFEFjaGlldmVtZW50R3JhZGVHb2xkEAISHAoYQWNoaWV2ZW1l",
            "bnRHcmFkZVBsYXRpbnVtEAMqLwoIVGltZVR5cGUSDwoLVGltZVR5cGVOb24Q",
            "ABISCg5UaW1lVHlwZVNlY29uZBABKj8KDVNob3BSZXNldFR5cGUSFAoQU2hv",
            "cFJlc2V0VHlwZU5vbhAAEhgKFFNob3BSZXNldFR5cGVGb3JldmVyEAFiBnBy",
            "b3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Schema.Protobuf.Enums.ErrorCode), typeof(global::Schema.Protobuf.Enums.PlatformType), typeof(global::Schema.Protobuf.Enums.BattleType), typeof(global::Schema.Protobuf.Enums.ClassType), typeof(global::Schema.Protobuf.Enums.ChatType), typeof(global::Schema.Protobuf.Enums.ItemType), typeof(global::Schema.Protobuf.Enums.AchievementGrade), typeof(global::Schema.Protobuf.Enums.TimeType), typeof(global::Schema.Protobuf.Enums.ShopResetType), }, null));
    }
    #endregion

  }
  #region Enums
  public enum ErrorCode {
    [pbr::OriginalName("ErrorCodeFail")] Fail = 0,
    [pbr::OriginalName("ErrorCodeSuccess")] Success = 1,
  }

  public enum PlatformType {
    [pbr::OriginalName("PlatformTypeWindows")] Windows = 0,
    [pbr::OriginalName("PlatformTypeGooglePlay")] GooglePlay = 1,
    [pbr::OriginalName("PlatformTypeGameCenter")] GameCenter = 2,
    [pbr::OriginalName("PlatformTypeSteam")] Steam = 3,
    [pbr::OriginalName("PlatformTypeDevice")] Device = 4,
  }

  public enum BattleType {
    [pbr::OriginalName("BattleTypeFFA")] Ffa = 0,
    [pbr::OriginalName("BattleTypeTF")] Tf = 1,
  }

  public enum ClassType {
    [pbr::OriginalName("ClassTypeJun")] Jun = 0,
    [pbr::OriginalName("ClassTypeAra")] Ara = 1,
  }

  public enum ChatType {
    [pbr::OriginalName("ChatTypeNormal")] Normal = 0,
    [pbr::OriginalName("ChatTypeWhisper")] Whisper = 1,
    [pbr::OriginalName("ChatTypeParty")] Party = 2,
    [pbr::OriginalName("ChatTypeClan")] Clan = 3,
    [pbr::OriginalName("ChatTypeGameEveryone")] GameEveryone = 4,
    [pbr::OriginalName("ChatTypeGameTeam")] GameTeam = 5,
    [pbr::OriginalName("ChatTypeSystem")] System = 6,
  }

  public enum ItemType {
    [pbr::OriginalName("ItemTypeNon")] Non = 0,
    [pbr::OriginalName("ItemTypeCash")] Cash = 1,
    [pbr::OriginalName("ItemTypeGold")] Gold = 2,
    [pbr::OriginalName("ItemTypeExperience")] Experience = 3,
    [pbr::OriginalName("ItemTypeCharacter")] Character = 4,
    [pbr::OriginalName("ItemTypeSkin")] Skin = 5,
    [pbr::OriginalName("ItemTypeHelmet")] Helmet = 6,
    [pbr::OriginalName("ItemTypeArmor")] Armor = 7,
    [pbr::OriginalName("ItemTypePotion")] Potion = 8,
    [pbr::OriginalName("ItemTypeBuff")] Buff = 9,
    [pbr::OriginalName("ItemTypeBundle")] Bundle = 10,
    [pbr::OriginalName("ItemTypeBox")] Box = 11,
  }

  public enum AchievementGrade {
    [pbr::OriginalName("AchievementGradeBronze")] Bronze = 0,
    [pbr::OriginalName("AchievementGradeSilver")] Silver = 1,
    [pbr::OriginalName("AchievementGradeGold")] Gold = 2,
    [pbr::OriginalName("AchievementGradePlatinum")] Platinum = 3,
  }

  public enum TimeType {
    [pbr::OriginalName("TimeTypeNon")] Non = 0,
    [pbr::OriginalName("TimeTypeSecond")] Second = 1,
  }

  public enum ShopResetType {
    [pbr::OriginalName("ShopResetTypeNon")] Non = 0,
    [pbr::OriginalName("ShopResetTypeForever")] Forever = 1,
  }

  #endregion

}

#endregion Designer generated code
