// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Guild.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Schema.Protobuf.Message.Guild {

  /// <summary>Holder for reflection information generated from Guild.proto</summary>
  public static partial class GuildReflection {

    #region Descriptor
    /// <summary>File descriptor for Guild.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GuildReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgtHdWlsZC5wcm90bxIdU2NoZW1hLlByb3RvYnVmLk1lc3NhZ2UuR3VpbGQa",
            "C0VudW1zLnByb3RvGgpEYXRhLnByb3RvYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Schema.Protobuf.Enums.EnumsReflection.Descriptor, global::Schema.Protobuf.DataReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
